SELECT R.ID_RECEITA, u.NOME_USUARIO, R.NOME_RECEITA, R.TIPO_RECEITA, R.CALORIAS,
R.MEDIA_PRECO, R.TEMPO_PREPARO,R.TIPO_REFEICAO, R.MODO_PREPARO, I.NOME, I.QUANTIDADE, R.CLASSIFICACAO
    FROM APP_RECEITAS.RECEITA R
    INNER JOIN APP_RECEITAS.INGREDIENTE I ON R.ID_RECEITA = I.ID_RECEITA
    INNER JOIN APP_RECEITAS.USUARIO u ON R.ID_USUARIO = u.ID_USUARIO
    WHERE MEDIA_PRECO <= ?;
SELECT R.ID_RECEITA, u.NOME_USUARIO, R.NOME_RECEITA, R.TIPO_RECEITA, R.CALORIAS,
R.MEDIA_PRECO, R.TEMPO_PREPARO,R.TIPO_REFEICAO, R.MODO_PREPARO, I.NOME, I.QUANTIDADE, R.CLASSIFICACAO
    FROM APP_RECEITAS.RECEITA R
    INNER JOIN APP_RECEITAS.INGREDIENTE I ON R.ID_RECEITA = I.ID_RECEITA
    INNER JOIN APP_RECEITAS.USUARIO u ON R.ID_USUARIO = u.ID_USUARIO
    ORDER BY MEDIA_PRECO;
SELECT R.ID_RECEITA, u.NOME_USUARIO, R.NOME_RECEITA, R.TIPO_RECEITA, R.CALORIAS,
R.MEDIA_PRECO, R.TEMPO_PREPARO,R.TIPO_REFEICAO, R.MODO_PREPARO, I.NOME, I.QUANTIDADE, R.CLASSIFICACAO
    FROM APP_RECEITAS.RECEITA R
    INNER JOIN APP_RECEITAS.INGREDIENTE I ON R.ID_RECEITA = I.ID_RECEITA
    INNER JOIN APP_RECEITAS.USUARIO u ON R.ID_USUARIO = u.ID_USUARIO
    ORDER BY MEDIA_PRECO DESC;
SELECT R.ID_RECEITA, u.NOME_USUARIO, R.NOME_RECEITA, R.TIPO_RECEITA, R.CALORIAS,
R.MEDIA_PRECO, R.TEMPO_PREPARO,R.TIPO_REFEICAO, R.MODO_PREPARO, I.NOME, I.QUANTIDADE, R.CLASSIFICACAO
    FROM APP_RECEITAS.RECEITA R
    INNER JOIN APP_RECEITAS.INGREDIENTE I ON R.ID_RECEITA = I.ID_RECEITA
    INNER JOIN APP_RECEITAS.USUARIO u ON R.ID_USUARIO = u.ID_USUARIO
    WHERE TEMPO_PREPARO <= ?;
SELECT R.ID_RECEITA, u.NOME_USUARIO, R.NOME_RECEITA, R.TIPO_RECEITA, R.CALORIAS,
R.MEDIA_PRECO, R.TEMPO_PREPARO,R.TIPO_REFEICAO, R.MODO_PREPARO, I.NOME, I.QUANTIDADE, R.CLASSIFICACAO
    FROM APP_RECEITAS.RECEITA R
    INNER JOIN APP_RECEITAS.INGREDIENTE I ON R.ID_RECEITA = I.ID_RECEITA
    INNER JOIN APP_RECEITAS.USUARIO u ON R.ID_USUARIO = u.ID_USUARIO
    WHERE I.NOME = ?;
SELECT R.ID_RECEITA, U.NOME_USUARIO, R.NOME_RECEITA, R.TIPO_RECEITA, R.CALORIAS, R.MEDIA_PRECO
, R.TEMPO_PREPARO, R.TIPO_REFEICAO, R.MODO_PREPARO, I.NOME, I.QUANTIDADE, R.CLASSIFICACAO
    FROM APP_RECEITAS.RECEITA r
    INNER JOIN APP_RECEITAS.INGREDIENTE i ON R.ID_RECEITA = I.ID_RECEITA INNER JOIN APP_RECEITAS.USUARIO U
    ON R.ID_USUARIO = U.ID_USUARIO WHERE TIPO_REFEICAO = ? AND CALORIAS BETWEEN ? AND ?;
SELECT R.ID_RECEITA, u.NOME_USUARIO, R.NOME_RECEITA, R.TIPO_RECEITA, R.CALORIAS,
R.MEDIA_PRECO, R.TEMPO_PREPARO,R.TIPO_REFEICAO, R.MODO_PREPARO, I.NOME, I.QUANTIDADE, R.CLASSIFICACAO
    FROM APP_RECEITAS.RECEITA R
    INNER JOIN APP_RECEITAS.INGREDIENTE I ON R.ID_RECEITA = I.ID_RECEITA
    INNER JOIN APP_RECEITAS.USUARIO u ON R.ID_USUARIO = u.ID_USUARIO
    WHERE TIPO_RECEITA = ?;
SELECT R.ID_RECEITA, u.NOME_USUARIO, R.NOME_RECEITA, R.TIPO_RECEITA, R.CALORIAS,
R.MEDIA_PRECO, R.TEMPO_PREPARO,R.TIPO_REFEICAO, R.MODO_PREPARO, I.NOME, I.QUANTIDADE, R.CLASSIFICACAO
    FROM APP_RECEITAS.RECEITA R
    INNER JOIN APP_RECEITAS.INGREDIENTE I ON R.ID_RECEITA = I.ID_RECEITA
    INNER JOIN APP_RECEITAS.USUARIO u ON R.ID_USUARIO = u.ID_USUARIO
    WHERE TIPO_REFEICAO = ?;
SELECT AVG(N.CLASSIFICACAO) AS MEDIA_NOTA FROM APP_RECEITAS.RECEITA R
    INNER JOIN APP_RECEITAS.NOTA N ON R.ID_RECEITA = N.ID_RECEITA
    WHERE R.ID_RECEITA = ?;
SELECT R.ID_RECEITA, u.NOME_USUARIO, R.NOME_RECEITA, R.TIPO_RECEITA, R.CALORIAS,
R.MEDIA_PRECO, R.TEMPO_PREPARO,R.TIPO_REFEICAO, R.MODO_PREPARO, I.NOME, I.QUANTIDADE, R.CLASSIFICACAO
    FROM APP_RECEITAS.RECEITA R
    INNER JOIN APP_RECEITAS.INGREDIENTE I ON R.ID_RECEITA = I.ID_RECEITA
    INNER JOIN APP_RECEITAS.USUARIO u ON R.ID_USUARIO = u.ID_USUARIO
    WHERE R.ID_USUARIO = ?;
